from .high_performance_parser import (
    HighPerformanceStreamingJsonParser,
    ParseResult,
    ParseStatus,
    decode_complete_json,
    decode_complete_json_view,
    decode_ndjson,
    decode_ndjson_adaptive,
    decode_structural_partial_json,
    extract_complete_json_paths,
    extract_complete_json_typed_paths,
    extract_ndjson_paths,
    extract_ndjson_paths_native,
    extract_ndjson_typed_paths,
    extract_tuned_complete_json_paths,
    extract_tuned_json_paths,
    extract_tuned_ndjson_paths,
    make_complete_json_decoder,
    make_complete_json_typed_path_extractor,
    make_complete_json_view_decoder,
    make_json_path_extractor,
    make_ndjson_decoder,
    make_ndjson_path_extractor,
    make_ndjson_path_extractor_native,
    make_ndjson_typed_path_extractor,
    make_tuned_complete_json_decoder,
    make_tuned_complete_json_path_extractor,
    make_tuned_json_path_extractor,
    make_tuned_ndjson_decoder,
    make_tuned_ndjson_path_extractor,
    make_tuned_structural_partial_decoder,
)

__version__ = "0.2.2"

# The canonical public name points to the strict incremental implementation.
StreamingJsonParser = HighPerformanceStreamingJsonParser

__all__ = [
    "StreamingJsonParser",
    "__version__",
    "HighPerformanceStreamingJsonParser",
    "ParseResult",
    "ParseStatus",
    "decode_complete_json",
    "decode_complete_json_view",
    "decode_ndjson",
    "decode_ndjson_adaptive",
    "decode_structural_partial_json",
    "extract_complete_json_paths",
    "extract_complete_json_typed_paths",
    "extract_ndjson_paths",
    "extract_ndjson_paths_native",
    "extract_ndjson_typed_paths",
    "extract_tuned_complete_json_paths",
    "extract_tuned_json_paths",
    "extract_tuned_ndjson_paths",
    "make_complete_json_decoder",
    "make_complete_json_typed_path_extractor",
    "make_complete_json_view_decoder",
    "make_json_path_extractor",
    "make_ndjson_decoder",
    "make_ndjson_path_extractor",
    "make_ndjson_path_extractor_native",
    "make_ndjson_typed_path_extractor",
    "make_tuned_complete_json_decoder",
    "make_tuned_complete_json_path_extractor",
    "make_tuned_json_path_extractor",
    "make_tuned_ndjson_decoder",
    "make_tuned_ndjson_path_extractor",
    "make_tuned_structural_partial_decoder",
]
